# Generated by Django 4.2.2 on 2023-06-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nmae',
            new_name='name',
        ),
    ]
