# Generated by Django 4.2.2 on 2023-06-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_nmae_project_name'),
    ]

    operations = [
    ]
